[project]
name = "google-image-scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "drissionpage>=4.1.0.18",
    "loguru>=0.7.3",
    "requests>=2.32.3",
    "typer>=0.15.2",
    "yarl>=1.18.3",
]
